### ISSUE TITLE
Relicense under Apache or similar license?

### ISSUE THREAD

**Issue by micander** [dipman/oshdlc#1]
I badly want to use this library but my project contains closed-source code. I am willing to release my modifications and improvements to the library but I need to be able to link it into proprietary code. I'm developing for a microcontroller where dynamic linking is unavailable so static linking would have to be allowed.
Would you consider allowing use of your software under a license like the Apache or MIT? I fully understand if you stand behind the terms of the GPL and will write my own implementation if required.
Thank you very much for your consideration!

**Comment by dipman** [comment]
You can surely use the library as you desire. I would appreciate if you think reflecting your contributions to the code. 
Best regards.
